[workspace]
members = ["crates/*/*"]

exclude = [
  "crates/day-19/project",
  "crates/day-20/project",
  "crates/day-21/project",
  "crates/day-21/wapc-guest",
  "crates/day-22/project",
  "crates/day-22/wapc-guest",
]
